### ISSUE TITLE
The VLLM settings you used for Qwen2.5-Coder-32b-Instruct in the open-webui example?

### ISSUE THREAD

**Issue by lor-ai** [SecretiveShell/MCP-Bridge#51]
Hey, great project!
I've been able to get this working okay with Ollama, but with VLLM/Qwen, MCP-Bridge doesn't recognize the tool calls?
Here's the docker command I'm using:
docker run -d -it \
  --ipc=host \
  --runtime=nvidia \
  --gpus '"device=0,1"' \
  -e HUGGING_FACE_HUB_TOKEN=<HF_TOKEN> \
  -e VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 \
  --name vllm_qwenCoder \
  -v "C:/Users/lor/.cache/huggingface:/root/.cache/huggingface" \
  -v vllm_data:/vllm_data \
  -p 8000:8000 \
  --add-host=host.docker.internal:host-gateway \
  vllm/vllm-openai:latest \
  --model Qwen/CodeQwen1.5-7B-Chat-AWQ \
  --trust-remote-code \
  --quantization awq_marlin \
  --kv-cache-dtype fp8_e5m2 \
  --tensor-parallel-size 2 \
  --gpu-memory-utilization=0.95 \
  --enforce-eager
  --enable-auto-tool-choice \
  --tool-call-parser hermes 

Using the official VLLM docker image, via Docker Desktop on Windows 11, with open-webui client.
I've tried this with MCP-Bridge both dockerized and native, and tried adding "--chat-templatetool_chat_template_hermes.jinja", but in all cases MCP-Bridge fails to recognize the tool call and it ends up displayed in the chat.

Mind sharing what settings your running Qwen in VLLM with?
Thanks1

**Comment by SecretiveShell** [comment]
Here is the dockerfile I used the first time

```yaml
services:
  vllm_qwen2_5_32b_coder_instruct:
    image: vllm/vllm-openai:latest
    environment:
      - HUGGING_FACE_HUB_TOKEN=YOUR_TOKEN
    ports:
      - "8000:8000"
    volumes:
      - /large_models/base_models/llm:/models/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    ipc: host
    command: >
      --model "/models/Qwen2.5-Coder-32B-Instruct"
      --tensor-parallel-size 4
      --pipeline-parallel-size 1
      --trust-remote-code
      --swap-space 0
      --enable-auto-tool-choice
      --tool-call-parser llama3_json
```

Though I no longer recommend qwen coder due to a bug where the llm cannot call tools after the first assistant message. Regular qwen 32b works best with hermes and is a good model to try.

> I've tried this with MCP-Bridge both dockerized and native, and tried adding "--chat-templatetool_chat_template_hermes.jinja", but in all cases MCP-Bridge fails to recognize the tool call and it ends up displayed in the chat.

This is because the tool parser setup in vllm is not detecting the start of the tool call and is treating the generated tokens as part of the assistant message.
