### ISSUE TITLE
OPENWEBUI EXAMPLE

### ISSUE THREAD

**Issue by webcoderz** [SecretiveShell/MCP-Bridge#7]
hello i have hooked up openwebui and am proxying my models that are being ran with vllm on openai api mode via the mcp server and have owui hooked up to the http://mcp-bridge/v1/api endpoint and i keep getting an error when trying the example:

Cannot read properties of null (reading 'choices')

i got this on llama and qwen models and disabled streaming in openwebui

**Comment by SecretiveShell** [comment]
hi, are you able to provide more information to help me reproduce the issue?

specifically:
- are you running with or without docker
- can you send your config json
- do you have tool call parser enabled in vLLM and verified to be working
- do you get any errors in the log (ideally set the logging config to debug level)

**Comment by webcoderz** [comment]
Config is default you’ve provided , running inside docker , no logs , how can I set more thorough logging? And when I get models it says tool calling is enabled in vllm, how can I ensure it’s set up vllm side? I didn’t set up the vllm instance , thanks for responding quickly and this is a great base to use for mcp.

**Comment by webcoderz** [comment]
If I have to ; how do I enable tool calling? We mostly use llama and qwen; what are the flags you ran with?

**Comment by SecretiveShell** [comment]
> If I have to ; how do I enable tool calling? We mostly use llama and qwen; what are the flags you ran with?

here is a draft compose.yml file for qwen32B on 4x 3090s. The important part is the flags at the bottom with tool choice stuff.

```yaml
services:
  vllm_qwen2_5_32b_coder_instruct:
    image: vllm/vllm-openai:latest
    environment:
      - HUGGING_FACE_HUB_TOKEN=token
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    ipc: host
    command: >
      --model "Qwen/Qwen2.5-Coder-32B-Instruct"
      --tensor-parallel-size 4
      --pipeline-parallel-size 1
      --trust-remote-code
      --swap-space 0
      --enable-auto-tool-choice
      --tool-call-parser llama3_json
```
